skills_list = [
    "python",
    "java",
    "c++",
    "sql",
    "mysql",
    "flask",
    "django",
    "machine learning",
    "data analysis",
    "pandas",
    "numpy",
    "html",
    "css",
    "javascript",
    "bootstrap",
    "react",
    "node.js",
    "aws",
    "git",
    "github",
    "oop",
    "data structures",
    "algorithms",
    "communication",
    "problem solving"
]
